### ISSUE TITLE
Create list of information that program owners will need to know to participate in the PRAD1K.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#177]
As a program owner, I want to know how PRAD1k works so I can participate.

**Comment by dbhume** [comment]
So that I can...?

From: Loren Mullane
Sent: Tuesday, November 24, 2015 11:22 AM
To: BCDevExchange/BCDevExchange-app
Reply To: BCDevExchange/BCDevExchange-app
Subject: [BCDevExchange-app] Create list of information that program owners will need to know to participate in the PRAD1kl. (#177)



As a program owner, I want to know how PRAD1k works.

-

**Comment by lmullane** [comment]
The will be one list with topics selected by persona like this example: https://www.gov.uk/service-manual
