### ISSUE TITLE
Dockerize deployment environment

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-app#223]
As a developer, I want to to Dockerize (build a Dockerfile, define a build and deployment process) so that I can simplify the effort of provisioning new deployment environments and updating existing ones for BCDevExchange. I also want to be in a good position to potentially re-host the BCDevExchange application in a Docker-based PaaS platform.

**Comment by f-w** [comment]
This seems a good PRAD1K candidate. There are other work (that I am working on) in order to re-platform or creating additional BCDevExchange instances. The goal is to make the dockerized instances self-maintained by users, not by developers or system admins.

**Comment by kelpisland** [comment]
This one is higher priority than PRAD1K so we can get some critical mass running on our OpenShift POC

**Comment by ll911** [comment]
@kelpisland @f-w is the db separation completed?

**Comment by kelpisland** [comment]
Not that I know of - If needed let's just keep that work as part of this issue

**Comment by f-w** [comment]
A Dockerfile has been created so I am closing the ticket. 
The Dockerfile alone is inadequate to "clone" this web app, especially when setting up a CI environment with persistent data due to following limitations:
1. Unsuitable to capture local.json
2. Unsuitable to capture mutable data
3. Every docker build is a full build taking over 40min, which is too long comparing to current 10min incremental build.

**Comment by kelpisland** [comment]
@f-w can you open this as an issue in the BCDevOps/issues-solutions ? @watkinspd  has some insight into setting build options for the containers on the OS environment.

**Comment by f-w** [comment]
The limitations are applicable to basic docker approach. On a specific PAAS platform such as OS, there are ways to address them so I don't see them as blocking issues. Once I get it working, I can write a wiki to document the solution.
