### ISSUE TITLE
As a developer, I want to see work with listed on a profile page with columns for rewards, skills, so I can understand what I want to work on.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#229]
As a developer, I want to see work with listed on a profile page with columns for rewards, skills, so I can understand what I want to work on.

DOD:
Pull from GitHub API
Display labels in set columns (e.g. skills)
Include button linking to explanation of how process works (link to Wiki)
Include contextual content

Additional information:
Work is partly complete but more needs to be done to match the wireframe:
https://strategicinitiatives.mybalsamiq.com/projects/profilepage/BC%20Laws%202

**Comment by lmullane** [comment]
@f-w Please connect with @ragbay @sheaphillips and myself on this issue.

**Comment by f-w** [comment]
I have reviewed the wireframe. It's impossible to provide "Fork" and "pull requests" column because those data are attributed to a project, not to a issue. Besides, GH treats pull request as issue as well.

**Comment by f-w** [comment]
Some more design decisions and details:

1. Existing inline editable "Work With Us" section will be replaced by the issue list. The section will be hidden if list is empty.
2. Project column will be removed because a program has only one repo configured for now.
3. All BCDevX listed projects should adopt same tag color scheme in order to differentiate tags into Rewards and Skills Required category. Rewards tags should use dark blue #0052cc, and Skills Required tags should use yellow #fbca04.
4. The workflow blob will be replaced by something else because there will be issues without rewards.
5. Title "Work With Us" will be changed to "Code With Us"
6. "View Work on our board" will contain a link to waffle board, replacing existing "Work Underway" section.

**Comment by lmullane** [comment]
Couple more:

7. Remove "Go to GitHub" sections.
8. Include button "How to Participate" in "Code With Us" that links here: https://github.com/BCDevExchange/rapid-adoption/wiki
3. Put stats counter under the Code With Us section.
4. Change "Skills Required" button to "Contact Us" and anchor link to team photos below.
5. Remove Skills required section between Resources and Community as this will be a duplication of what appears in specific issues.

**Comment by lmullane** [comment]
@f-w The team liked the work on the profile page - no major changes. Here's the feedback and minor changes:

1. Change "Reward" to "Earn"
2. If there is no money to be earned (i.e. blue label) in the earned column, show a font awesome heart
3.  Change the label colour of skills from yellow to orange
4. Add an area below the code with us section that has inline editing, aligned left, white background. This is where we will link to the Kanban board.
