### ISSUE TITLE
Adding "work in progress"

### ISSUE THREAD

**Issue by ragbay** [BCDevExchange/BCDevExchange-app#284]
Related to timeboxing, showing work in progress on the Code with Us page. The in progress work might help the community avoid duplication of work and possibly self govern a timeboxing/reservation-type of approach.

DOD:

**Comment by ragbay** [comment]
assigned to @lmullane, @paulroberts68, and @ragbay as per sprint 21 planning session.

**Comment by paulroberts68** [comment]
I have spoken with Loren, Peter and Fred. We now have a wireframe design and content. Next step is for @f-w  to let us know if the app has permissions to alter assignees in GitHub and @lmullane to process the content through comms.

**Comment by f-w** [comment]
The app has to gain permission from program owner during their login to bcdevx. It's at the discretion of program owner to approve. Also because the app has no prior knowledge whether the to-be-login user is a program owner or not, the "write" permission request has to be extended to all BCDevX users. In addition, the write permission cannot be specific to a repo, but to all repos the user owns. This could be an excessive demand for majority of users. Currently BCDevX only ask permission to get user email.
